### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by Wangt-CN** [kuanghuei/SCAN#1]
Hi, your work is great!
But i can't find the pre-trained model that you refer to 'model.tar', can you give a link? Thank you very much!!
![image](https://user-images.githubusercontent.com/32795963/43043152-42aee6c8-8dbf-11e8-9d15-fd67350d1599.png)

**Comment by kuanghuei** [comment]
Sorry for the confusion. I didn't plan to release the pre-trained models. I have fixed the statement in README.
