### ISSUE TITLE
data

### ISSUE THREAD

**Issue by jasscia18** [kuanghuei/SCAN#10]
wget https://scanproject.blob.core.windows.net/scan-data/data.zip
Do you still have this data set? I have been unable to download it. Can you pass me a copy? Thanks

**Comment by kuanghuei** [comment]
There were people complaining about the Azure storage and the file is too big to download. I will try to see if I can find a time to host the chunked files somewhere else. In the meanwhile, please check the "Data pre-processing (Optional)" section for an alternative.
