### ISSUE TITLE
About the experiment in table 3 of your paper

### ISSUE THREAD

**Issue by Sisi0518** [kuanghuei/SCAN#12]
Hi, your work is a great contribution and the results are exciting! But I have some confusion about the experiment in Table 3.
The dataset uesd in experiment shown in Table 3 isn't mentioned. Which one is the dataset, MSCOCO or Flickr30k ?
There are methods named "Sum-Max t-i" and "Sum-Max i-t" in Table 3. But I found the loss function in your code can be chosen from 'LogSumExp', 'Max', 'Sum' and 'Mean'. What does "Sum-Max" mean?

**Comment by Sisi0518** [comment]
I found that  the loss function 'Max' or 'Sum' doesn't match the experiment "Sum-Max t-i" and "Sum-Max i-t" in Table 3. Because when choose 'Max' or 'Sum', it also uses the func_attention() to get attention.
But the experiment "Sum-Max t-i" and "Sum-Max i-t"  just calculate the cosine similarity without attention.
Is that right?

**Comment by kuanghuei** [comment]
I didn't include implementation of Sum-Max, but it can be easily modified from the code. Please check eq. 9 and eq. 10 for Sum-Max definition.

**Comment by Sisi0518** [comment]
Thanks for your quick replay! I,m sorry to bother you again, is the dataset used in experiment shown in Table 3 Flickr30K or MSCOCO? I found no dataset information in the table caption.

**Comment by Sisi0518** [comment]
I got it. Thank you so much.
