### ISSUE TITLE
Troubles when evaluating models on  COCO adding --fold5

### ISSUE THREAD

**Issue by miracle24** [kuanghuei/SCAN#14]
Hello. When I want to test the model on COCO with fold5, I met an error as follows:
![image](https://user-images.githubusercontent.com/10026242/54066730-48ffba00-4270-11e9-884e-f1619180e144.png). And I checked the code in evaluation.py. And I was confused about some codes, like: 
![image](https://user-images.githubusercontent.com/10026242/54066736-751b3b00-4270-11e9-8f54-6716a6032464.png)
 From the first image, you can see that variable img_embs.shape[0]=5000, and cap_embs.shape[0]=5000. Therefore, if i > 0, img_embs_shard with be empty, so does the cap_embs_shard, which, I think, is the reason for the problem which I met in the evaluation of COCO. But, I do not know how to fix, because I new in this field. And right now I am still a little confused about how to compute the evaluation score. Could you help me out. Thanks a lot.

**Comment by dfatimazohra** [comment]
Hi @miracle24, I'm having the same issue. Were you able to find the solution? Thanks.

**Comment by YAOYI626** [comment]
> Hi @miracle24, I'm having the same issue. Were you able to find the solution? Thanks.

Hi,
Have you fixed it? I'm stuck with it, too.

**Comment by YAOYI626** [comment]
Oh I got it. There is a little problem in [data.py](https://github.com/kuanghuei/SCAN/blob/01812aa98e2ebe39695c8906589b6fe66b2a0d6e/data.py#L33): when it tests in coco, it loads 'test_ims.npy' instead of 'testall_ims.npy'. I have fixed it. Sorry to bother you guys. And although it's simple, but I still hope the repo owner to declare the problem.

**Comment by kuanghuei** [comment]
@YAOYI626 It's not a bug. You should just use split='testall' for COCO.
