### ISSUE TITLE
I get nan while training

### ISSUE THREAD

**Issue by dfatimazohra** [kuanghuei/SCAN#16]
Hello,  I am training the model without changing any parameters. but I get "nan" while trainig: 
![error_SCAN](https://user-images.githubusercontent.com/18269204/60286015-ba1cb900-98c3-11e9-8444-80a8be5d8ab1.PNG)

Do you know what is causing that? Thank you.

**Comment by kuanghuei** [comment]
Hi, I am not exactly sure what is the cause. I personally never encounter this problem. Would you mind to provide more information?

**Comment by dfatimazohra** [comment]
Thanks for your reply. I think  Pytorch version was causing that. I'm not getting this issue anymore.

**Comment by kuanghuei** [comment]
Good to hear that it's solved. Wondering which version of Pytorch you were using?

**Comment by dfatimazohra** [comment]
I tried using both Pytorch 0.4 and 1.1

**Comment by kuanghuei** [comment]
If I remember correctly, pytorch 0.4 also worked for me.
