### ISSUE TITLE
about data pre-processing for flickr

### ISSUE THREAD

**Issue by fkxssaa** [kuanghuei/SCAN#17]
Hi Kuang-Huei,

Thanks for sharing the code! I'm trying to obtain bottom-up-attention features of Flickr 30K.
Could you please tell me how to obtain mapping between filename of image and its id?
e.g. '99' is in dev_ids.txt.  However there is no image named '99.jpg' in Flickr Dataset.

Thanks!

**Comment by kuanghuei** [comment]
I think the original Flickr 30k metadata contains image id? At least you can find the "imgid" field in the json metadata in [https://cs.stanford.edu/people/karpathy/deepimagesent/flickr30k.zip]. This is from Andrej Karpathy from [https://cs.stanford.edu/people/karpathy/deepimagesent/].
