### ISSUE TITLE
original .tsv file?

### ISSUE THREAD

**Issue by idejie** [kuanghuei/SCAN#21]
Recently, I read your paper at ECCV 2018,  ''Stacked Cross Attention for Image-Text Matching' , and notice your model used the pre-process dataset.
I know that the convert_data.py is used to transfer the .tsv files(generated from the peteanderson80/bottom-up-attention) to  {coco/flickr30k}_ims.py files.
While the .npy files only contain the images'  boxes-features extracted from Faster-RCNN, and I want use more informations from .tsv files.
But it's too difficult to me that installing the requirements  of peteanderson80/bottom-up-attention, such as Caffe I tried to install many times but failed.
Could you help me provide the original .tsv file?

**Comment by kuanghuei** [comment]
Unfortunately I don't have it anymore :(

**Comment by idejie** [comment]
Thanks

**Comment by atg93** [comment]
is it possible that we convert numpy array to original tsv file ?
