### ISSUE TITLE
something about data preprocessing

### ISSUE THREAD

**Issue by IRIS00123** [kuanghuei/SCAN#22]
Hello, can you provide the parameter of generate_tsv.py?

**Comment by kuanghuei** [comment]
Which parameter do you have question for? Peter's instruction seems pretty clear. If you have question regarding the code, maybe Peter would be a better person to ask?

**Comment by kuanghuei** [comment]
Closing this issue for now. I also don't have the exact parameter for generate_tsv.py, but I just followed Peter Anderson's instruction so maybe it would be better to ask him in the Bottom-Up repo.
