### ISSUE TITLE
Input data shape error

### ISSUE THREAD

**Issue by Luofan-KK** [kuanghuei/SCAN#3]
Hi, I want to use Pascal VOC dataset to train this model. But after I using bottom-up-attention model, your 'convert_data.py' report this :
`raise ValueError('all input arrays must have the same shape')`
But I have tried many models and networks in bottom-up-attention model, the output file don't have same shape. May I know which model and network you use to get same shape ?
Thank you

**Comment by kuanghuei** [comment]
I thought there is only one model (Faster R-CNN pretrained on visual genome) that Peter Anderson provided? Have you checked if your input tsv (output of Peter's script) has the correct format?

**Comment by Luofan-KK** [comment]
I've solved this problem. In bottom-up-attention model I have to set Max size and Min size. It used to be 100 and 10, and I set them both 36, then problem solved. Thank you.
