### ISSUE TITLE
Loading data error

### ISSUE THREAD

**Issue by Luofan-KK** [kuanghuei/SCAN#4]
Sorry to bother you again, but i met a difficult problem for me to solve.
When I train your model, it begins to load data. And get error in dev set. Here is the error report:

`python train.py --data_path data --data_name pascal --logger_name runs/pascal/ --model_name runs/pascal/ --max_violation --bi_gru
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.7.5 locally
Namespace(agg_func='LogSumExp', batch_size=128, bi_gru=True, cross_attn='t2i', data_name='pascal', data_path='data', embed_size=1024, grad_clip=2.0, img_dim=2048, lambda_lse=6.0, lambda_softmax=9.0, learning_rate=0.0002, log_step=10, logger_name='runs/pascal/', lr_update=15, margin=0.2, max_violation=True, model_name='runs/pascal/', no_imgnorm=False, no_txtnorm=False, num_epochs=30, num_layers=1, precomp_enc_type='basic', raw_feature_norm='clipped_l2norm', resume='', val_step=500, vocab_path='./vocab/', word_dim=300, workers=10)
train
dev
runs/pascal/
runs/pascal/
/home/user/scan/model.py:220: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  attn = nn.Softmax()(attn*smooth)
/home/user/scan/model.py:452: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  self.logger.update('Le', loss.data[0], img_emb.size(0))
/home/user/scan/model.py:472: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  clip_grad_norm(self.params, self.grad_clip)
2018-08-23 21:54:29,157 Epoch: [0][9/32]        Eit 10  lr 0.0002  Le 63.2367 (67.5972) Time 0.803 (0.000)      Data 0.093 (0.000)
2018-08-23 21:54:36,654 Epoch: [0][19/32]       Eit 20  lr 0.0002  Le 60.4930 (64.5193) Time 0.777 (0.000)      Data 0.040 (0.000)
2018-08-23 21:54:44,191 Epoch: [0][29/32]       Eit 30  lr 0.0002  Le 60.3090 (63.2567) Time 0.741 (0.000)      Data 0.040 (0.000)
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main()
  File "train.py", line 137, in main
    rsum = validate(opt, val_loader, model)
  File "train.py", line 203, in validate
    model, val_loader, opt.log_step, logging.info)
  File "/home/user/scan/evaluation.py", line 100, in encode_data
    for i, (images, captions, lengths, ids) in enumerate(data_loader):
  File "/home/user/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/user/scan/data.py", line 56, in __getitem__
    image = torch.Tensor(self.images[img_id])
IndexError: index 100 is out of bounds for axis 0 with size 100
`
The shape of each set is : train 800, dev 100, test 100. And train set has 3999 caps, dev has 500, test has 499 caps. 
What should I do to solve this problem?
Thank you for your kindness, and may this issues can help others.

**Comment by Luofan-KK** [comment]
I think I solved this problem. You really inspired me, that I begin to think about dev set length. Then, I find that in data.py, line 45
``

**Comment by kuanghuei** [comment]
I see. dev sets are supposed to be 5000 for coco and flickr30k. This only affects test time.
