### ISSUE TITLE
Data download problem

### ISSUE THREAD

**Issue by FabScarr1** [kuanghuei/SCAN#40]
Hi, thanks for your paper and repo.
I'am interested in running your code but when I try to download the data
e.g. 
wget https://scanproject.blob.core.windows.net/scan-data/vocab.zip

I obtain:
Resolving scanproject.blob.core.windows.net (scanproject.blob.core.windows.net)... failed: Unknown Host. .
wget: unable to resolve host address 'scanproject.blob.core.windows.net'

Is this a temporary issue or the data are no more available?

Thanks

**Comment by HYY0508** [comment]
Have you found anything suitable? Thanks!

**Comment by kuanghuei** [comment]
The data links have been restored.

**Comment by beam-fly** [comment]
Is this data link still valid?
