### ISSUE TITLE
Broken link downloading dataset

### ISSUE THREAD

**Issue by DavidAmatGlovo** [kuanghuei/SCAN#45]
The link to download the data seems to be broken again https://scanproject.blob.core.windows.net/scan-data/data.zip. Could you please reestablish it again? Thanks

**Comment by mokii** [comment]
Same problem, have you resolve it?

**Comment by kuanghuei** [comment]
Closing the issue now. I don't think the old link is anywhere in the repo. Feel free to reopen it.
