### ISSUE TITLE
Problem on downloading the data.zip

### ISSUE THREAD

**Issue by kevin8new** [kuanghuei/SCAN#5]
Hi, your work is a great contribution and the results are exciting!

I want to run your code, but have some trouble downloading the data.zip from https://scanproject.blob.core.windows.net/scan-data/data.zip. The speed is really slow and there is sometimes connection interruption. 

Can you please upload the data.zip to somewhere else, maybe google disk? Can you please split the data from different datasets,  and split the models and data separately for packaging? 

Thanks a lot for you effort!

**Comment by kevin8new** [comment]
I can only reach about 60KB/s when downloading the data.zip, but its size is 34GB...

Could you please split the data from different datasets, and split the models and data separately for packaging? Maybe I can download some of them in this way, for quickly starting from evaluating your well-trained models.

Sorry for the trouble and thanks a lot!

**Comment by kuanghuei** [comment]
I just tried with comcast network within the states and it's 2.5mb/s. Do you want to try using a proxy?

I just upload a data package without precomputed image features at:
https://scanproject.blob.core.windows.net/scan-data/data_no_feature.zip
You can compute the bottom-up image feature from raw images locally following the instructions.

By the way, the pre-trained model is not provided.

**Comment by kevin8new** [comment]
Ok, thanks a lot for your help.

I will download the data and train the model.
