### ISSUE TITLE
Urgent need for another download link 

### ISSUE THREAD

**Issue by akira-l** [kuanghuei/SCAN#52]
Could you provide another download link? The current link always fails after downloading for serval hours. 
![image](https://user-images.githubusercontent.com/9478838/184617500-2eb9976b-907f-4bae-a78b-ad735387e10f.png)
I have already changed three servers to download this data, and it always fails.

**Comment by kuanghuei** [comment]
I started hosting the data on Kaggle now and updated the data link in readme. This should allow you to download individual files. Hope this helps.
