### ISSUE TITLE
Dataset download issue

### ISSUE THREAD

**Issue by KomalKrishM** [kuanghuei/SCAN#53]
The link provided for downloading the data.zip file is not working. I mean the link fails to download the 34 GB data. It starts download initially and popups a "connection closed error" and starts downloading from the starting, eventually not downloading complete data. Please resolve this issue. Thanks in advance!

**Comment by kuanghuei** [comment]
I started hosting the data on Kaggle now and updated the data link in readme. This should allow you to download individual files.
