### ISSUE TITLE
Data download and environmental issues

### ISSUE THREAD

**Issue by Daydaylight** [kuanghuei/SCAN#55]
1. The link you provided cannot download data now, can you provide the download link again?

2. Does it have to be Python 2.7 and PyTorch 0.3? It seems that this version is no longer available for download.

Looking forward to your reply

**Comment by cjc20000323** [comment]
Does this issue solved? I cannot download data either. Do you find ways to solve?

**Comment by Daydaylight** [comment]
> Does this issue solved? I cannot download data either. Do you find ways to solve?

I haven't found a solution yet

**Comment by cjc20000323** [comment]
您好，我已收到您的邮件，请您知悉。

**Comment by cjc20000323** [comment]
That sounds too bad

**Comment by kuanghuei** [comment]
Sorry for the long-time broken link. I started hosting the data on Kaggle now and updated the data link in readme.

With very small changes, it should be compatible with Python 3.x and newer PyTorch. Contributions are welcome.
