### ISSUE TITLE
The result cannot be reproduced

### ISSUE THREAD

**Issue by Boreas-pxl** [kuanghuei/SCAN#56]
Thanks for your open-sourcing! When I run this code, the results I got are not as good as those given in your paper. 

This is the result on flickr30k using SCAN t-i LSE (λ1 = 9, λ2 = 6):
![1666153796304](https://user-images.githubusercontent.com/74233822/196597968-20f42210-cda2-493c-aaa5-51c83ef9511f.jpg)

My environment is python2.7 and pytorch0.4.1 with Geforce RTX 2080. 

I'll appreciate for your reply.

Again sorry to bother you.

**Comment by Boreas-pxl** [comment]
Oh，sry, it's my mistake, I didn't pass in the proper parameters. The result is normal。 ：）

**Comment by Daydaylight** [comment]
> Thanks for your open-sourcing! When I run this code, the results I got are not as good as those given in your paper.
> 
> This is the result on flickr30k using SCAN t-i LSE (λ1 = 9, λ2 = 6): ![1666153796304](https://user-images.githubusercontent.com/74233822/196597968-20f42210-cda2-493c-aaa5-51c83ef9511f.jpg)
> 
> My environment is python2.7 and pytorch0.4.1 with Geforce RTX 2080.
> 
> I'll appreciate for your reply.
> 
> Again sorry to bother you.
Could you please provide a download connection for flickr30k?
