### ISSUE TITLE
The link to the dataset is broken

### ISSUE THREAD

**Issue by zhuang2002** [kuanghuei/SCAN#58]

**Comment by cjc20000323** [comment]
Does this issue solved? I cannot download data either. Do you find ways to solve?

**Comment by woodfrog** [comment]
Hi, I downloaded the data before, and [here](https://drive.google.com/file/d/1iY6S-w-vG-4T_v9OvlFkZ1GDPzX5YVtl/view?usp=sharing) is a copy. The file structures in the zip file might be different from the original version provided by SCAN, and you can check the readme of [my repo](https://github.com/woodfrog/vse_infty#data) for details. Hope this helps.

**Comment by cjc20000323** [comment]
您好，我已收到您的邮件，请您知悉。

**Comment by huaerr** [comment]
> 
请问您这个问题解决了吗

**Comment by cjc20000323** [comment]
您好，我已收到您的邮件，请您知悉。

**Comment by Lxier** [comment]
请问您下载到数据了吗

**Comment by cjc20000323** [comment]
您好，我已收到您的邮件，请您知悉。

**Comment by kuanghuei** [comment]
Sorry for the long-time broken link. I started hosting the data on Kaggle now and updated the data link in readme.
