### ISSUE TITLE
About visualising attention

### ISSUE THREAD

**Issue by Wangt-CN** [kuanghuei/SCAN#8]
Great work!!
However, I am very confused that how could you visualize the attention？
Because the image regions is about instance and is unordered.
Moreover, I really want to ask for the python script for visualization :) Thank you

**Comment by jasscia18** [comment]
Hello, do you still have the data set of this code? I have been unable to download it, and it is always interrupted.Thank you

**Comment by kuanghuei** [comment]
@Wangt-CN Sorry I see your point now. There were position information from Peter Anderson's feature extraction code, but I dropped it in data release. You can follow the instruction in README to re-extract image features and region information using Peter's tool.
